/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAppPortfoliosRouteImport } from './routes/_authenticated/app.portfolios'
import { Route as AuthenticatedAppGroupGroupIdRouteImport } from './routes/_authenticated/app.group.$groupId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppPortfoliosRoute =
  AuthenticatedAppPortfoliosRouteImport.update({
    id: '/app/portfolios',
    path: '/app/portfolios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppGroupGroupIdRoute =
  AuthenticatedAppGroupGroupIdRouteImport.update({
    id: '/app/group/$groupId',
    path: '/app/group/$groupId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/portfolios': typeof AuthenticatedAppPortfoliosRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/app/group/$groupId': typeof AuthenticatedAppGroupGroupIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/portfolios': typeof AuthenticatedAppPortfoliosRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/app/group/$groupId': typeof AuthenticatedAppGroupGroupIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/app/portfolios': typeof AuthenticatedAppPortfoliosRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/app/group/$groupId': typeof AuthenticatedAppGroupGroupIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/app/portfolios' | '/app/' | '/app/group/$groupId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/app/portfolios' | '/app' | '/app/group/$groupId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/app/portfolios'
    | '/_authenticated/app/'
    | '/_authenticated/app/group/$groupId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/portfolios': {
      id: '/_authenticated/app/portfolios'
      path: '/app/portfolios'
      fullPath: '/app/portfolios'
      preLoaderRoute: typeof AuthenticatedAppPortfoliosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app/group/$groupId': {
      id: '/_authenticated/app/group/$groupId'
      path: '/app/group/$groupId'
      fullPath: '/app/group/$groupId'
      preLoaderRoute: typeof AuthenticatedAppGroupGroupIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppPortfoliosRoute: typeof AuthenticatedAppPortfoliosRoute
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
  AuthenticatedAppGroupGroupIdRoute: typeof AuthenticatedAppGroupGroupIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppPortfoliosRoute: AuthenticatedAppPortfoliosRoute,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
  AuthenticatedAppGroupGroupIdRoute: AuthenticatedAppGroupGroupIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
